name = "ai-novel-api"
main = "src/index.js"
compatibility_date = "2025-06-01"

[[d1_databases]]
binding = "DB"
database_name = "ai-novel-db"
database_id = "988ce9e7-e3e2-4582-a58c-fffea4013c60"

[[r2_buckets]]
binding = "COVERS"
bucket_name = "novel-covers"